# Generated by Django 4.1.7 on 2023-03-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
