# Generated by Django 4.1.7 on 2023-03-18 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chambre', models.CharField(max_length=100)),
                ('id_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='tools')),
                ('id_chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.chambre')),
                ('id_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel')),
            ],
        ),
    ]
