# Generated by Django 4.1.7 on 2023-03-18 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_chambre_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_chambre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.chambre')),
                ('id_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
