# Generated by Django 4.1.7 on 2023-03-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_photo_hotelphoto_chambrephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelphoto',
            name='id_chambre',
        ),
    ]
