# Generated by Django 4.1.7 on 2023-03-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_chambre_id_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='id_hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel'),
        ),
    ]
