# Generated by Django 4.1.7 on 2023-03-25 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_chambre_id_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='nombre_disponible',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chambre',
            name='numero_chambre',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chambre',
            name='prix_chambre',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
