# Generated by Django 4.1.7 on 2023-03-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_chambre_nombre_disponible_chambre_numero_chambre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='prix_chambre',
        ),
    ]
