# Generated by Django 4.1.7 on 2023-03-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_chambre_prix_chambre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chambre',
            old_name='nombre_disponible',
            new_name='prix_chambre',
        ),
    ]
