# Generated by Django 4.1.7 on 2023-03-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_rename_nombre_disponible_chambre_prix_chambre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambrephoto',
            name='id_chambre',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_chambre',
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
