# Generated by Django 4.1.7 on 2023-03-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_chambrephoto_id_chambre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chambre', models.CharField(max_length=100)),
                ('numero_chambre', models.BigIntegerField()),
                ('nombre_disponible', models.BigIntegerField(default=10)),
                ('prix_chambre', models.BigIntegerField()),
                ('id_hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='chambrephoto',
            name='id_chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.chambre'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_chambre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.chambre'),
        ),
    ]
